GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tIiwiaWF0IjoxNjEzMzg3ODIzfQ.KCgb6AsJAfiHXYZtiDIW558T1ScV9kHBMyCrSPuUwyQ

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Tom"
}